import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync,existsSync} from 'node:fs';
const moduleURL = new URL('../portfolio-assets/comparison-model.mjs', import.meta.url);
const pack = kind => JSON.parse(readFileSync(new URL(`../data/published-runs-${kind}.json`,import.meta.url)));
async function model(){assert.ok(existsSync(moduleURL),'P2 comparison model must exist');return import(moduleURL.href);}
async function fixture(){const m=await model();return {m,runs:['historical','synthetic'].flatMap(k=>m.readRuns(pack(k)))};}
const pick=(runs,symbol,task='trend')=>runs.find(r=>r.symbol===symbol&&r.taskId===task);
test('all 15 original published runs pass independent record validation',async()=>{const {m,runs}=await fixture();assert.equal(runs.length,15);for(const r of runs)assert.deepEqual(m.validateRun(r),[],r.symbol+' '+r.taskId);});
test('AAPL comparison uses exact recorded equity, benchmark and B minus A',async()=>{const {m,runs}=await fixture();const a=pick(runs,'AAPL'),b=pick(runs,'AAPL','hold'),c=m.compareRuns(a,b);assert.equal(c.ok,true);assert.equal(c.delta.netPnl,2.66);assert.equal(c.delta.fees,-0.78);assert.equal(c.delta.fillCount,-26);assert.equal(c.rows.length,390);assert.equal(c.rows.at(-1).a,100004.02);assert.equal(c.rows.at(-1).b,100006.68);assert.equal(c.rows.at(-1).benchmark,100009.81);assert.equal(c.rows[0].time,a.result.barStart);});
test('all same-symbol pairs compare without modifying their source',async()=>{const {m,runs}=await fixture();const before=JSON.stringify(runs);for(const symbol of ['AAPL','MSFT','NVDA','^GSPC','ASML'])for(const ta of ['trend','hold','range'])for(const tb of ['trend','hold','range'])if(ta!==tb)assert.equal(m.compareRuns(pick(runs,symbol,ta),pick(runs,symbol,tb)).ok,true);assert.equal(JSON.stringify(runs),before);});
test('identical run is not a two-strategy comparison',async()=>{const {m,runs}=await fixture();assert.equal(m.compareRuns(runs[0],runs[0]).ok,false);});
test('different symbol and synthetic market are rejected with reasons',async()=>{const {m,runs}=await fixture();for(const b of [pick(runs,'MSFT'),pick(runs,'ASML')]){const c=m.compareRuns(pick(runs,'AAPL'),b);assert.equal(c.ok,false);assert.ok(c.reasons.length);assert.equal(c.rows,undefined);}});
for(const key of ['initialCash','feeBps','slippageBps','maxPosition'])test(`reject unequal ${key}`,async()=>{const {m,runs}=await fixture();const a=pick(runs,'AAPL'),b=structuredClone(pick(runs,'AAPL','hold'));b.result.config[key]+=1;assert.equal(m.compareRuns(a,b).ok,false);});
for(const key of ['version','currency','multiplier','timing','execution','rounding','funding','terminal','benchmarkDescription','benchmarkUnits'])test(`reject changed policy ${key}`,async()=>{const {m,runs}=await fixture();const a=pick(runs,'AAPL'),b=structuredClone(pick(runs,'AAPL','hold'));b.result.policy[key]=typeof b.result.policy[key]==='number'?99:'different';assert.equal(m.compareRuns(a,b).ok,false);});
for(const key of ['datasetChecksum','datasetId','barStart'])test(`reject changed ${key}`,async()=>{const {m,runs}=await fixture();const b=structuredClone(pick(runs,'AAPL','hold'));b.result[key]=key==='barStart'?b.result[key]+60000:'different';assert.equal(m.compareRuns(pick(runs,'AAPL'),b).ok,false);});
test('missing matching evidence is not proof of compatibility',async()=>{const {m,runs}=await fixture();const a=structuredClone(pick(runs,'AAPL')),b=structuredClone(pick(runs,'AAPL','hold'));delete a.result.policy.version;delete b.result.policy.version;assert.equal(m.compareRuns(a,b).ok,false);delete a.meta.runtimeSha256;delete b.meta.runtimeSha256;assert.equal(m.compareRuns(a,b).ok,false);});
test('runtime changes are rejected even when policy name is unchanged',async()=>{const {m,runs}=await fixture();const b=structuredClone(pick(runs,'AAPL','hold'));b.meta.runtimeSha256['training/engine.py']='0'.repeat(64);assert.equal(m.compareRuns(pick(runs,'AAPL'),b).ok,false);});
test('truncated run and changed benchmark cannot produce a partial comparison',async()=>{const {m,runs}=await fixture();for(const mode of ['truncated','benchmark']){const b=structuredClone(pick(runs,'AAPL','hold'));if(mode==='truncated')b.points.pop();else b.points[30].benchmark+=1;assert.equal(m.compareRuns(pick(runs,'AAPL'),b).ok,false);}});
for(const key of ['netPnl','finalEquity','fees','fillCount','maxDrawdownPct'])test(`reject corrupted recorded ${key}`,async()=>{const {m,runs}=await fixture();const b=structuredClone(pick(runs,'AAPL','hold'));b.result.metrics[key]+=10;assert.equal(m.compareRuns(pick(runs,'AAPL'),b).ok,false);});
test('zero-trade NVDA result is valid, not missing',async()=>{const {m,runs}=await fixture();const c=m.compareRuns(pick(runs,'NVDA'),pick(runs,'NVDA','range'));assert.equal(c.ok,true);assert.equal(c.b.result.metrics.fillCount,0);});
test('unknown transport and non-finite tuple are rejected',async()=>{const m=await model();let p=pack('historical');p.markets.historical.$transport.version=999;assert.throws(()=>m.readRuns(p),/transport/i);p=pack('historical');p.markets.historical.runs[0].result.equity[0][0]=null;assert.throws(()=>m.readRuns(p),/equity|finite/i);});
test('source and replay URLs preserve market, task and exact run id',async()=>{const {m,runs}=await fixture();for(const r of runs){const links=m.runLinks(r);assert.equal(new URL(links.report,'https://example.test').searchParams.get('market'),r.marketKind);assert.ok(links.report.endsWith('view=review&run='+r.result.runId));assert.ok(links.source.endsWith('#/studio?source='+r.taskId));}});
test('unknown run IDs fail visibly; omitted IDs default deterministically',async()=>{const {m,runs}=await fixture();const d=m.selectPair(runs,new URLSearchParams());assert.equal(d.a.symbol,'AAPL');assert.equal(d.b.taskId,'hold');assert.throws(()=>m.selectPair(runs,new URLSearchParams('a=missing')),/Unknown/);const s=m.selectPair(runs,new URLSearchParams('a='+pick(runs,'ASML','hold').result.runId));assert.equal(s.b.symbol,'ASML');assert.notEqual(s.a.taskId,s.b.taskId);});
