"""Chromium presentation-copy acceptance on a local candidate, without server writes."""
import functools
import http.server
import os
import threading
import unittest
from pathlib import Path
from playwright.sync_api import sync_playwright, expect

ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/'qa'/'copy'
RUN='3df0ac0f357353bac0e991eed16d3f78458611ddf2f541cfdf44d7839529b1b2'
class Handler(http.server.SimpleHTTPRequestHandler):
    def log_message(self,*args):pass

class CopyBrowser(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        OUT.mkdir(parents=True,exist_ok=True)
        cls.server=http.server.ThreadingHTTPServer(('127.0.0.1',0),functools.partial(Handler,directory=str(ROOT)))
        threading.Thread(target=cls.server.serve_forever,daemon=True).start()
        cls.base=f'http://127.0.0.1:{cls.server.server_port}'
        cls.pw=sync_playwright().start(); opts={'headless':True}
        if os.environ.get('CHROMIUM_EXECUTABLE'):opts['executable_path']=os.environ['CHROMIUM_EXECUTABLE']
        cls.browser=cls.pw.chromium.launch(**opts)
    @classmethod
    def tearDownClass(cls):
        cls.browser.close();cls.pw.stop();cls.server.shutdown();cls.server.server_close()
    def setUp(self):
        self.context=self.browser.new_context(viewport={'width':1440,'height':900})
        self.page=self.context.new_page();self.page.set_default_timeout(12000)
        self.errors=[];self.writes=[];self.js=[]
        self.page.on('pageerror',lambda e:self.errors.append(str(e)))
        self.page.on('request',lambda r:self.writes.append(r.url) if r.method!='GET' else None)
        self.page.on('response',lambda r:self.js.append((r.url,r.status)) if r.url.split('?')[0].endswith('.js') else None)
    def tearDown(self):
        self.page.screenshot(path=str(OUT/(self._testMethodName+'.png')),full_page=True)
        self.context.close();self.assertEqual(self.errors,[]);self.assertEqual(self.writes,[])
    def goto(self,path):
        response=self.page.goto(self.base+path,wait_until='networkidle')
        if response:self.assertEqual(response.status,200)
    def closed_notes(self):
        self.assertNotIn('No live market connection or real orders.',self.page.locator('body').inner_text())
        self.assertNotIn('Not live · Not advice',self.page.locator('body').inner_text())
    def test_overview_modes_keep_clear_short_labels(self):
        for kind in ['synthetic','historical']:
            self.goto('/training.html?market='+kind+'#/training')
            expect(self.page.locator('.d-overview .d-say')).to_have_text(kind.capitalize()+' prices · Simulated trading')
            expect(self.page.locator('.d-bar')).to_contain_text('390')
            self.closed_notes()
    def test_trading_labels_match_market_on_desktop_and_phone(self):
        for width,height in [(1440,600),(390,844)]:
            self.page.set_viewport_size({'width':width,'height':height})
            for kind in ['synthetic','historical']:
                self.goto('/training.html?market='+kind+'#/market')
                label=self.page.locator('.d-say:visible, .d-say-phone:visible')
                expect(label).to_contain_text(kind.capitalize()+' prices · Simulated trading')
                self.assertNotIn('Optibook',label.inner_text())
                self.assertLess(len(label.inner_text()),130)
                self.closed_notes()
                self.page.screenshot(path=str(OUT/f'trading-{kind}-{width}.png'),full_page=True)
    def test_training_details_open_by_keyboard_and_keep_full_boundaries(self):
        self.goto('/training.html#/market')
        expect(self.page.locator('.d-say')).to_contain_text('Synthetic prices')
        self.assertEqual(self.page.locator('.copy-site-notes').evaluate('(n)=>getComputedStyle(n).backgroundColor'),self.page.locator('#root section.pt-desk').evaluate('(n)=>getComputedStyle(n).backgroundColor'))
        notes=self.page.locator('#simulation-details');summary=notes.locator('summary')
        summary.focus();self.page.keyboard.press('Enter')
        expect(notes).to_have_attribute('open','')
        for value in ['390 one-minute bars','generated by P.Book','does not connect to Optibook','No live market connection or real orders.','Python execution requires the local P.Book runtime.','not investment advice']:
            expect(notes).to_contain_text(value)
        self.page.keyboard.press('Enter');self.assertIsNone(notes.get_attribute('open'))
    def test_profile_home_lab_details_and_source_context_remain(self):
        for path in ['/','/profile.html#project-pbook','/lab.html']:
            self.goto(path);details=self.page.locator('details.copy-details').first
            summary=details.locator('summary');summary.focus();self.page.keyboard.press('Enter')
            expect(details).to_have_attribute('open','')
            expect(details).to_contain_text('Yahoo Finance')
            expect(details).to_contain_text('Synthetic prices: scenarios generated by P.Book.')
            expect(details).to_contain_text('No live market connection or real orders.')
        expect(self.page.locator('details.copy-details')).to_contain_text('private research vault')
    def test_report_replay_and_ide_load_new_copy_bundles(self):
        for route in ['#/market?view=review&run='+RUN,'#/market?view=replay&run='+RUN,'#/studio']:
            self.goto('/training.html?market=historical'+route)
            if route=='#/studio':
                expect(self.page.get_by_role('button',name='Download .py',exact=True)).to_be_visible()
                expect(self.page.locator('.ev-disclosure')).to_contain_text('Historical and synthetic prices · Simulated trading')
                expect(self.page.locator('.demo-source-note')).to_contain_text('this site does not execute Python.')
            else:expect(self.page.locator('body')).to_contain_text('AAPL')
            self.closed_notes()
        loaded={url.split('/')[-1] for url,status in self.js if status==200}
        self.assertTrue({'training-demo-v1.js','review-copy-v1.js','market-copy-v1.js','studio-demo-v1.js'}<=loaded,loaded)
        self.assertFalse(any(n in loaded for n in ['training-CI29yBEs.js','ReviewPage-DYeWlPpm.js','MarketPage-3-BVK_gJ.js','studioRoute.static-Dtkr_XUq.js']))
    def test_notes_work_with_javascript_disabled(self):
        self.context.close();self.context=self.browser.new_context(java_script_enabled=False);self.page=self.context.new_page()
        self.goto('/training.html');expect(self.page.locator('noscript h1')).to_contain_text('P.Book')
        self.page.locator('#simulation-details summary').click()
        expect(self.page.locator('#simulation-details .copy-details-body')).to_be_visible()
        expect(self.page.locator('#simulation-details')).to_contain_text('not investment advice')
    def test_responsive_pages_keep_primary_copy_and_no_overflow(self):
        for width,height in [(1440,600),(390,844),(320,740)]:
            self.page.set_viewport_size({'width':width,'height':height})
            for path in ['/','/profile.html#project-pbook','/lab.html','/training.html#/studio']:
                self.goto(path)
                if '#/studio' in path:expect(self.page.get_by_role('button',name='Download .py',exact=True)).to_be_visible()
                self.assertFalse(self.page.evaluate('document.documentElement.scrollWidth>innerWidth+1'),f'{path}@{width}')
                self.page.screenshot(path=str(OUT/f'copy-{width}-{path.split("#")[0].replace("/","") or "home"}.png'),full_page=True)
        self.page.emulate_media(color_scheme='dark');self.goto('/training.html#/market')
        expect(self.page.locator('.d-say-phone')).to_contain_text('Synthetic prices · Simulated trading')

if __name__=='__main__':unittest.main(verbosity=2)
