import test from 'node:test';
import assert from 'node:assert/strict';
import {existsSync,readFileSync} from 'node:fs';
import {readRuns} from '../portfolio-assets/comparison-model.mjs';
const url=new URL('../portfolio-assets/quality-model.mjs',import.meta.url);
async function model(){assert.ok(existsSync(url),'Quality model must implement drawdown and public replay links');return import(url.href);}
const rows=values=>values.map((equity,barIndex)=>({equity,barIndex,label:`minute ${barIndex+1}`}));
const entry=(values=[100,90,120,105])=>({published:true,marketKind:'historical',result:{runId:'a'.repeat(64),datasetChecksum:'b'.repeat(64),equity:rows(values),metrics:{initialEquity:100}}});
test('drawdown uses the earlier running peak, not independent extrema',async()=>{const m=await model(),d=m.drawdownRange(rows([100,90,120,105]),100);assert.equal(d.pct,12.5);assert.equal(d.peak.barIndex,2);assert.equal(d.trough.barIndex,3);assert.equal(d.amount,15);});
test('future high is never paired with an earlier trough',async()=>{const m=await model(),d=m.drawdownRange(rows([100,80,140]),100);assert.equal(d.pct,20);assert.equal(d.peak.barIndex,0);assert.equal(d.trough.barIndex,1);});
test('initial equity is a real prior high when the first observation loses value',async()=>{const m=await model(),d=m.drawdownRange(rows([90,95]),100);assert.equal(d.pct,10);assert.equal(d.peak.label,'Start');assert.equal(d.peak.initial,true);assert.equal(d.trough.barIndex,0);});
test('choose the earliest equal maximum and earliest equal peak deterministically',async()=>{const m=await model();let d=m.drawdownRange(rows([100,100,80,100,80]),100);assert.equal(d.peak.barIndex,0);assert.equal(d.trough.barIndex,2);d=m.drawdownRange(rows([100,90,200,180]),100);assert.equal(d.trough.barIndex,1);});
for(const values of [[100,100,100],[100,110,120],[]])test(`no drawdown creates no invented interval: ${values}`,async()=>{const m=await model(),d=m.drawdownRange(rows(values),100);assert.equal(d.pct,0);assert.equal(d.peak,null);assert.equal(d.trough,null);});
test('bankruptcy has a 100 percent drawdown',async()=>{const m=await model();assert.equal(m.drawdownRange(rows([100,0]),100).pct,100);});
for(const value of [NaN,Infinity,-1,null,'100'])test(`invalid equity ${value} is not quietly charted`,async()=>{const m=await model();assert.throws(()=>m.drawdownRange(rows([100,value]),100));});
test('all 15 drawdowns reconcile with retained published percentages without mutating records',async()=>{const m=await model();let count=0;for(const kind of ['historical','synthetic']){const pack=JSON.parse(readFileSync(new URL(`../data/published-runs-${kind}.json`,import.meta.url)));for(const r of readRuns(pack)){const before=JSON.stringify(r);const e=r.result.equity.map((v,i)=>({equity:v[0],barIndex:i,label:String(i)}));const d=m.drawdownRange(e,r.result.config.initialCash);assert.ok(Math.abs(d.pct-r.result.metrics.maxDrawdownPct)<1e-10,`${r.symbol}/${r.taskId}`);assert.equal(JSON.stringify(r),before);count++;}}assert.equal(count,15);});
test('share URL whitelists only public identity, tape and one-based minute',async()=>{const m=await model(),e=entry(),s=m.replayLink('https://example.test/training.html?secret=x#/studio?draft=private',e,2),u=new URL(s),p=new URLSearchParams(u.hash.split('?')[1]);assert.equal(u.pathname,'/training.html');assert.equal(u.search,'?market=historical');assert.deepEqual([...p.keys()],['view','run','tape','minute']);assert.equal(p.get('minute'),'3');assert.equal(m.readReplayMoment(s,e).cursor,2);assert.equal(m.readReplayMoment(s,e).status,'valid');assert.ok(!s.includes('private'));});
test('first and final minutes including a zero-trade run are shareable',async()=>{const m=await model(),e=entry([100,100,100]);for(const i of [0,2])assert.equal(m.readReplayMoment(m.replayLink('https://example.test',e,i),e).cursor,i);});
test('synthetic link explicitly preserves its market',async()=>{const m=await model(),e=entry();e.marketKind='synthetic';const link=m.replayLink('https://example.test',e,1);assert.equal(new URL(link).search,'?market=synthetic');assert.equal(m.readReplayMoment(link,e).status,'valid');});
for(const value of [-1,4,1.2,NaN])test(`reject invalid share cursor ${value}`,async()=>{const m=await model();assert.throws(()=>m.replayLink('https://example.test',entry(),value));});
test('private/local runs cannot be shared',async()=>{const m=await model(),e=entry();e.published=false;assert.throws(()=>m.replayLink('https://example.test',e,0));});
test('old run links do not override remembered cursor',async()=>{const m=await model();assert.equal(m.readReplayMoment('https://example.test/training.html?market=historical#/market?view=replay&run='+entry().result.runId,entry()).status,'absent');});
for(const minute of ['0','-1','5','1.5','1e0','','999999999999999999'])test(`reject malformed or out-of-range minute ${minute}`,async()=>{const m=await model(),e=entry(),u=new URL(m.replayLink('https://example.test',e,0));u.hash=u.hash.replace('minute=1','minute='+minute);assert.equal(m.readReplayMoment(u.href,e).status,'invalid');});
for(const param of ['run','tape','minute'])test(`reject duplicate ${param} parameters`,async()=>{const m=await model(),e=entry(),s=m.replayLink('https://example.test',e,0);assert.equal(m.readReplayMoment(s+'&'+param+'=1',e).status,'invalid');});
test('wrong run, tape, market or missing tape is visibly invalid, never clamped',async()=>{const m=await model(),e=entry(),s=m.replayLink('https://example.test',e,0);for(const v of [s.replace('a'.repeat(64),'c'.repeat(64)),s.replace('b'.repeat(64),'c'.repeat(64)),s.replace('market=historical','market=synthetic'),s.replace('&tape='+'b'.repeat(64),'')])assert.equal(m.readReplayMoment(v,e).status,'invalid');});

test('runtime-normalized published entry keeps market identity inside result',async()=>{const m=await model(),e=entry();e.result.marketKind=e.marketKind;delete e.marketKind;const link=m.replayLink('https://example.test',e,2);assert.equal(m.readReplayMoment(link,e).cursor,2);});
