"""Apply reviewed presentation-only changes without overwriting original runtime assets.

Run after the P1/P2 generators. Derived UI bundles use new URLs; the retained
exported bundles, market records, strategy code and provenance remain unchanged.
"""
from __future__ import annotations
import argparse
import hashlib
import json
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
MARK='<!-- public-copy:v1 -->'
CSS='<link rel="stylesheet" href="/portfolio-assets/presentation-copy.css?v=copy-1">'
MIXED='Historical 1-min OHLC · 10 Sep 2026 · Yahoo Finance, and synthetic Optibook tapes — depth, cash, orders, fills and P&amp;L simulated by P.Book’s local runtime · Not live · Not advice'


def replace(text,old,new,count=1):
    if text.count(old)!=count:
        raise ValueError('Copy source structure changed: '+old[:95])
    return text.replace(old,new)


def details(extra='',identifier=''):
    ident=f' id="{identifier}"' if identifier else ''
    return f'''<details class="copy-details"{ident}><summary>Data &amp; simulation details</summary>
<div class="copy-details-body"><p>Historical prices: retained Yahoo Finance one-minute OHLC for 10 Sep 2026, with 390 one-minute bars per instrument. Synthetic prices: scenarios generated by P.Book.</p>
<p>The order book, trading activity and account results are simulated. No live market connection or real orders.</p>
<p>Synthetic contract definitions reference retained Optibook course metadata; the generated prices come from P.Book. This site does not connect to Optibook.</p>
<p>Edit and export strategies in the browser. Python execution requires the local P.Book runtime.</p>{extra}</div></details>'''


def derive_module(path,spec,config,root):
    source=(root/path).read_bytes()
    if hashlib.sha256(source).hexdigest()!=config['immutableInputs'][path]:
        raise ValueError('Upstream bundle changed; review the copy map before regenerating: '+path)
    text=source.decode('utf-8')
    for item in spec['replacements']:
        text=replace(text,item['old'],item['new'],item['count'])
    # New UI bundle URLs isolate browser caches. The original CSS stays in assets/.
    for old,new in config['imports'].items():text=text.replace(old,new)
    return text


def transform(name,text):
    if MARK in text:return text
    if name=='index.html':
        for cls,old in [
          ('wide','Historical 1-min OHLC · 10 Sep 2026 · Yahoo Finance — depth, cash, fills and P&amp;L are simulated by P.Book’s local runtime · Not live · Not advice'),
          ('narrow','Historical 1-min OHLC · 10 Sep 2026 · Yahoo Finance. Depth, cash, fills and P&amp;L simulated by P.Book · Not live · Not advice')]:
            text=replace(text,f'<p class="th-say th-say-{cls}">{old}</p>',f'<p class="th-say th-say-{cls}">Historical prices · Simulated trading</p>')
        text=replace(text,MIXED,'Historical and synthetic prices · Simulated trading')
        needle='<div class="s1-foot">'
        start=text.index(needle);end=text.index('</div>',start)
        text=text[:end]+details(identifier='home-market-details')+text[end:]
        text=replace(text,'Synthetic · Optibook','Synthetic · P.Book')
    elif name=='profile.html':
        text=replace(text,'Each figure names the data it was measured on. Results from simulations and historical diagnostics are labelled as such; none are live trading results.','Results are labelled by dataset and evaluation setting.')
        text=replace(text,'A browser trading desk that replays retained one-minute tapes against a simulated order book, with a Python strategy engine that runs locally and publishes its runs.','An interactive trading simulator with replayable sessions and a local Python strategy engine.')
        text=replace(text,'<p>'+MIXED+'.</p>','<p>Historical and synthetic prices · Simulated trading</p>')
        text=replace(text,'Twelve of the 15 published runs use four historical tapes of 390 one-minute bars each; the remaining three use synthetic tapes. Python does not execute on the public site — runs are published from a local engine and replayed here.','Explore 15 published runs: 12 historical and 3 synthetic. Edit strategies here; run Python locally with P.Book.')
        start=text.index('<div class="technical-note">',text.index('id="project-pbook"'))
        end=text.index('</div>',start)
        text=text[:end]+details()+text[end:]
    elif name=='lab.html':
        text=replace(text,'<p class="lab-say">Counts describe a private research vault. The runs are simulated by P.Book on historical 1-min OHLC · 10 Sep 2026 · Yahoo Finance · Not live · Not advice</p>',
                     '<p class="lab-say">Published simulations · Historical and synthetic prices</p>'+details('<p>Catalogue counts describe a private research vault. Only the linked reports and code are public.</p>'))
    elif name=='training.html':
        text=replace(text,'./assets/training-CI29yBEs.js','/portfolio-assets/training-copy-v1.js')
        old='P.Book — a training desk that replays saved one-minute tapes with a simulated order book, a Python strategy runtime, and published runs ranked under identical conditions.'
        text=replace(text,old,'P.Book — an interactive trading simulator with replayable sessions and editable Python strategies. Python execution runs locally.',2)
        text=replace(text,'P.Book is a training desk that replays saved one-minute tapes with a simulated order book and a\n        simulated account. The desk itself needs JavaScript. These pages do not:','P.Book is an interactive trading simulator. The desk needs JavaScript; project pages and simulation details remain available below:')
        text=replace(text,'</body>', '<footer class="copy-site-notes" aria-label="Simulation information">'+details('<p>For learning and research, not investment advice.</p>', 'simulation-details')+'</footer>\n</body>')
    else:raise ValueError('Unreviewed page: '+name)
    return replace(text,'</head>',MARK+'\n'+CSS+'\n</head>')


def apply(root=ROOT,check=False):
    root=Path(root)
    config=json.loads((root/'scripts/presentation_copy.json').read_text(encoding='utf-8'))
    for path,sha in config['immutableInputs'].items():
        if hashlib.sha256((root/path).read_bytes()).hexdigest()!=sha:
            raise ValueError('Immutable public input changed: '+path)
    updates={name:transform(name,(root/name).read_text(encoding='utf-8')) for name in ['index.html','profile.html','lab.html','training.html']}
    for path,spec in config['modules'].items():updates[spec['output']]=derive_module(path,spec,config,root)
    release=json.loads((root/'release.json').read_text())
    hashes={n:hashlib.sha256(t.encode()).hexdigest() for n,t in updates.items()}
    css='portfolio-assets/presentation-copy.css';hashes[css]=hashlib.sha256((root/css).read_bytes()).hexdigest()
    for group in ['publicEnhancements','publicP2']:
        for name in release[group]['files']:
            if name in hashes:release[group]['files'][name]=hashes[name]
    release['publicCopy']={'version':config['version'],'baseCommit':config['baseCommit'],'files':hashes,
       'note':'Reviewed presentation strings and UI import paths only. Original exported bundles, all data and published strategy sources are retained unchanged.'}
    updates['release.json']=json.dumps(release,indent=2,ensure_ascii=False)+'\n'
    changed=[n for n,t in updates.items() if not (root/n).exists() or (root/n).read_text(encoding='utf-8')!=t]
    if check:
        if changed:raise SystemExit('Presentation copy needs regeneration: '+', '.join(changed))
    else:
        for n in changed:(root/n).write_text(updates[n],encoding='utf-8',newline='')
    print('Presentation copy: '+(', '.join(changed) if changed else 'already current'))
    return changed

if __name__=='__main__':
    p=argparse.ArgumentParser();p.add_argument('--root',type=Path,default=ROOT);p.add_argument('--check',action='store_true');a=p.parse_args();apply(a.root,a.check)
